logging.config=classpath:logback-base.xml

logging.level.it.pagopa.pn.pdfraster=${PN_PDF_RASTER_LOGGING_LEVEL_ROOT:debug}

spring.task.execution.pool.max-size=${PN_PDF_RASTER_TASK_EXECUTION_POOL_MAX_SIZE:500}

jetty.maxConnectionsPerDestination=${PN_PDF_RASTER_MAX_CONNECTIONS_PER_DESTINATION:2048}

spring.codec.max-in-memory-size=${SPRING_CODEC_MAX_IN_MEMORY_SIZE:10MB}

pn.pdfraster.parameter-name=${PN_PDF_RASTER_PARAMETERS:pn-PDFRaster}
pn.pdfraster.max-thread-pool-size=${PN_PDF_RASTER_MAX_THREAD_POOL_SIZE:100}
pn.pdfraster.max-transformation-retry=10
pn.pdfraster.sqs.transformation-queue-name=${PN_PDF_RASTER_TRANSFORMATION_QUEUE_NAME:pn-ss-transformation-raster-queue}
pn.pdfraster.sqs.max-messages=${PN_PDF_RASTER_SQS_MAX_MESSAGES:10}
pn.pdfraster.sqs.retry-strategy.max-attempts=${PN_PDF_RASTER_SQS_RETRY_STRATEGY_MAX_ATTEMPTS:3}
pn.pdfraster.sqs.retry-strategy.min-backoff=${PN_PDF_RASTER_SQS_RETRY_STRATEGY_MIN_BACKOFF:3}

pn.env.runtime=PROD
spring.application.name=PN-PDFRASTER

pn.log.trace-id-header=X-Amzn-Trace-Id
pn.log.jti-header=x-pagopa-pn-jti
pn.log.pn-uid-header=x-pagopa-pn-uid
pn.log.pn-cx-type-header=x-pagopa-pn-cx-type
pn.log.pn-cx-groups-header=x-pagopa-pn-cx-groups
pn.log.pn-cx-role-header=x-pagopa-pn-cx-role
pn.log.cx-id-header=x-pagopa-pn-cx-id

management.endpoints.web.exposure.include=health,metrics,loggers


