AWSTemplateFormatVersion: '2010-09-09'
Description: Some storage with input and output

Parameters:
  ProjectName:
    Type: String
    Description: "Nome dell'ambiente destinazione"

  # Unused but required by CD pipeline
  MicroserviceNumber:
    Type: Number
    Description: 'An unique number that identify the microservice inside the ECS cluster'

  # Unused but required by CD pipeline
  TemplateBucketBaseUrl:
    Type: String
    Description: 'URL da cui caricare i frammenti di template di infrastruttura'
  
  Version:
    Type: String
    Description: 'Keep track of used projects commitIds'
  
  CdcKinesisSourceStreamArn:
    Type: String
    Description: 'Where to send CDC'

  AlarmSNSTopicName:
    Type: String
    Description: 'Topic alarm'
    
  LogsKinesisSourceStreamArn:
    Type: String
    Description: 'Where to send Logs'

  LogRetention:
    Type: Number
    Default: 14

Resources:

  EcsLogGroup:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain    
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/log-group.yaml"
      Parameters:
        LogGroupName: !Sub '${ProjectName}-PDFRaster'
        LogsKinesisSourceStreamArn: !Ref LogsKinesisSourceStreamArn
        LogGroupRetention: !Ref LogRetention

  PnSsTransformationRasterStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TemplateURL: !Sub '${TemplateBucketBaseUrl}/fragments/sqs-queue.yaml'
      Parameters:
        QueueName: 'pn-ss-transformation-raster-queue'
        SqsManagedSseEnabled: true
        ContentBasedDeduplication: 'true'
        HasDLQ: 'true'
        MaxReceiveCount: 10
        QueueHasAlarm: 'false'
        AlarmSNSTopicName: !Ref AlarmSNSTopicName
        VisibilityTimeout: 60

Outputs:

  EcsLogGroup:
    Value: !GetAtt EcsLogGroup.Outputs.LogGroupName

